name: Upload Python Package

on:
  release:
    types: [published]
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build

    - name: Upload to file.io
      id: upload
      run: |
        FILE_PATH=$(find dist -name "*.whl")
        echo "Uploading ${FILE_PATH} to file.io"
        RESPONSE=$(curl -F "file=@${FILE_PATH}" https://file.io)
        echo "Upload Response: ${RESPONSE}"
        echo "::set-output name=url::$(echo $RESPONSE | jq -r .link)"

    - name: Log upload URL
      run: |
        echo "File uploaded to URL: ${{ steps.upload.outputs.url }}"
